nome = input('Diga seu nome: ')
idade = input('Qual sua idade ')
peso = input('Quanto você pesa: ')
altura = input('Qual sua altura: ')
telefone = input('Passa o zap: ')
print(f'Nome: {nome};')
print(f'Idade: {idade};')
print(f'Peso: {peso};')
print(f'Altura: {altura};')
print(f'Telefone: {telefone}.')